version: '3.8'

services:
  db:
    image: postgres:15.12
    container_name: task_tracker_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gtt_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tracker_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d gtt_db" ]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_tracker_back
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3322:3322"
    networks:
      - tracker_network
volumes:
  pgdata:

networks:
  tracker_network: