port: "3322"

mode: "prod"

dev:
  db:
    host: "localhost"
    port: 5432
    username: "postgres"
    dbname: "gtt_db"
    sslmode: "disable"
prod:
  db:
    host: "db"
    port: 5432
    username: "postgres"
    dbname: "gtt_db"
    sslmode: "disable"

password:
  hash_salt: "funny#!monkey12"

token:
  key: "qweds1fkp231safka"