# .github/workflows/ci.yml
name: CI for Go API

on:
  push:
    branches: [ main ] # Запускать при пуше в main ветку
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Получаем код из репозитория

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1' # Укажите вашу версию Go

      - name: Build
        run: go build ./...

  deploy:
    needs: build-and-test # Запускать после успешной сборки и тестов
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd go_task_tracker.back
            git pull origin main
            go build -o golang_back
            sudo systemctl restart golang_back.service
